spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev #开发环境
  application:
    name: microcloud-config-dev
  app:
    info: blackhe microcloud
    version: 0.0.1
    desc: xxxxxx
  sericut:888
---

spring:
  profiles: test #测试环境
  application:
    name: microcloud-config-test

#此文件的编码格式必须是UTF-8
