spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev #开发环境
  application:
    name: microcloud-config-dev

---

spring:
  profiles: test #测试环境
  application:
    name: microcloud-config-test

#此文件的编码格式必须是UTF-8